/*
 *      OFFICIAL NOTIFICATION: the following CONFIDENTIAL and PROPRIETARY
 * 	property legend shall not be removed from this source code module
 * 	for any reason.
 *
 *	This program is the CONFIDENTIAL and PROPRIETARY property
 *	of FairCom(R) Corporation. Any unauthorized use, reproduction or
 *	transfer of this computer program is strictly prohibited. The
 *      contents of this file may not be disclosed to third parties, copied or
 *      duplicated in any form, in whole or in part, without the prior written
 *      permission of the FairCom(R) Corporation.
 *
 *      Copyright (c) 1992 - 2024 FairCom Corporation.
 *	This is an unpublished work, and is subject to limited distribution and
 *	restricted disclosure only. ALL RIGHTS RESERVED.
 *
 *			RESTRICTED RIGHTS LEGEND
 *	Use, duplication, or disclosure by the Government is subject to
 *	restrictions set forth in subparagraph (c)(1)(ii) of the Rights in
 * 	Technical Data and Computer Software clause at DFARS 252.227-7013, and/or
 *      in similar or successor clauses in the FAR, DOD or NASA FAR Supplement.
 *      Unpublished rights reserved under the Copyright Laws of the United States.
 *	FairCom Corporation, 6300 West Sugar Creek Drive, Columbia, MO 65203.
 *
 *	c-treeACE(tm)	Version 13
 */


#ifdef ctPFNAMES

/* size of the pf_fnm array */
#define PF_FNM_SIZE 256

CTPF_FNM pf_fnm[PF_FNM_SIZE] = {
{ NULL,			CTPF_NONE },
{ "PUTFIL",		CTPF_HASFILNO },
{ "UPDCURI",		CTPF_HASDATNO },
{ "DELFIL",		CTPF_HASFILNO },
{ "LKISAM",		CTPF_NONE },
{ "DELREC",		CTPF_HASDATNO },
{ "ALCSET",		CTPF_NONE },
{ "CHGSET",		CTPF_NONE },
{ "DELVREC",		CTPF_HASDATNO },
{ "CLISAM",		CTPF_NONE },
{ "STPUSR",		CTPF_NONE },
{ "FRESET",		CTPF_NONE },
{ "CLSFIL",		CTPF_HASFILNO },
{ "TRANEND",		CTPF_NONE },
{ "TRANRST",		CTPF_NONE },
{ "TRANABT",		CTPF_NONE },
{ "?? 16 ??",		CTPF_NONE },
{ "CLRFIL",		CTPF_HASDATNO },
{ "DELRFIL",		CTPF_HASDATNO },
{ "ALCBAT",		CTPF_NONE },
{ "CHGBAT",		CTPF_NONE },
{ "FREBAT",		CTPF_NONE },
{ "PERFORM",		CTPF_NONE },
{ "USERLIST",		CTPF_NONE },
{ "USERINFO",		CTPF_NONE },
{ "CTKLUSR",		CTPF_NONE },
{ "CTTESTFUNC",		CTPF_NONE },
{ "CHGICON",		CTPF_NONE },
{ "CLSICON",		CTPF_NONE },
{ "CTFLUSH",		CTPF_HASFILNO },
{ "CTCHKPNT",		CTPF_NONE },
{ "TRANABTX",		CTPF_NONE },
{ "CHGHST",		CTPF_NONE },
{ "FREHST",		CTPF_NONE },
{ "SAVPCLR",		CTPF_NONE },
{ "TESTHUGE",		CTPF_NONE },
{ "ctRENFIL",		CTPF_HASFILNO },
{ "UPDCIDX",		CTPF_HASKEYNO },
{ "SETFLTR",		CTPF_HASDATNO },
{ "ADDUSR",		CTPF_NONE },
{ "ADDREC",		CTPF_HASDATNO },
{ "RWTREC",		CTPF_HASDATNO },
{ "NXTREC",		CTPF_HASFILNO },
{ "PRVREC",		CTPF_HASFILNO },
{ "FRSREC",		CTPF_HASFILNO },
{ "LSTREC",		CTPF_HASFILNO },
{ "RRDREC",		CTPF_HASDATNO },
{ "NXTSET",		CTPF_HASKEYNO },
{ "PRVSET",		CTPF_HASKEYNO },
{ "SETALTSEQ",		CTPF_HASKEYNO },
{ "GETALTSEQ",		CTPF_HASKEYNO },
{ "SETDEFBLKX",		CTPF_HASFILNO },
{ "MIDSET",		CTPF_HASKEYNO },
{ "PUTDODAX",		CTPF_HASDATNO },
{ "SETVARBYTS",		CTPF_HASFILNO },
{ "FRSVSET",		CTPF_HASKEYNO },
{ "LSTVSET",		CTPF_HASKEYNO },
{ "MIDVSET",		CTPF_HASKEYNO },
{ "TRANRDY",		CTPF_NONE },
{ "SYSMON",		CTPF_NONE },
{ "WRTVREC",		CTPF_HASDATNO },
{ "RDVREC",		CTPF_HASDATNO },
{ "REDREC",		CTPF_HASDATNO },
{ "WRTREC",		CTPF_HASDATNO },
{ "SETCURI",		CTPF_HASDATNO },
{ "RETREC",		CTPF_HASDATNO },
{ "RETVREC",		CTPF_HASDATNO },
{ "reset_cur",		CTPF_NONE },
{ "SETCURI",		CTPF_NONE },
{ "EQLVREC",		CTPF_HASKEYNO },
{ "GTEVREC",		CTPF_HASKEYNO },
{ "LTEVREC",		CTPF_HASKEYNO },
{ "GTVREC",		CTPF_HASKEYNO },
{ "LTVREC",		CTPF_HASKEYNO },
{ "GETMNAME",		CTPF_NONE },
{ "GETNAM",		CTPF_HASFILNO },
{ "GETSEG",		CTPF_HASKEYNO },
{ "GETMAP",		CTPF_HASDATNO },
{ "SECURITY",		CTPF_HASFILNO },
{ "SYSLOG",		CTPF_NONE },
{ "FRSSET",		CTPF_HASKEYNO },
{ "LSTSET",		CTPF_HASKEYNO },
{ "EQLREC",		CTPF_HASKEYNO },
{ "GTEREC",		CTPF_HASKEYNO },
{ "LTEREC",		CTPF_HASKEYNO },
{ "GTREC",		CTPF_HASKEYNO },
{ "LTREC",		CTPF_HASKEYNO },
{ "REDIREC",		CTPF_HASDATNO },
{ "STPUSRA",		CTPF_NONE },
{ "CHGUSR",		CTPF_NONE },
{ "CREISAM",		CTPF_HASISAMBLK },
{ "OPNISAM",		CTPF_HASISAMBLK },
{ "TRANISO",		CTPF_NONE },
{ "DELIFIL",		CTPF_HASIFILtfilno },
{ "RBLIFIL",		CTPF_HASIFIL },
{ "CREIFIL",		CTPF_HASIFIL },
{ "CLIFIL",		CTPF_HASIFILtfilno },
{ "OPNIFIL",		CTPF_HASIFIL },
{ "PRMIIDX",		CTPF_HASIFILdfilno },
{ "TMPIIDX",		CTPF_HASIFILdfilno },
{ "PUTIFIL",		CTPF_HASIFIL },
{ "CMPIFIL",		CTPF_HASIFIL },
{ "EXPIFIL",		CTPF_NONE },
{ "RBLIIDX",		CTPF_HASIFILdfilno },
{ "NXTVREC",		CTPF_HASFILNO },
{ "PRVVREC",		CTPF_HASFILNO },
{ "FRSVREC",		CTPF_HASFILNO },
{ "LSTVREC",		CTPF_HASFILNO },
{ "NXTVSET",		CTPF_HASKEYNO },
{ "PRVVSET",		CTPF_HASKEYNO },
{ "INTREE",		CTPF_NONE },
{ "INTISAM",		CTPF_NONE },
{ "SETFLTRN",		CTPF_HASDATNO },
{ "RESETFLTR",		CTPF_HASDATNO },
{ "RENIFIL",		CTPF_HASIFIL },
{ "SETNODE",		CTPF_NONE },
{ "UNDOFLEX",		CTPF_NONE },
{ "ctSETSEG",		CTPF_NONE },
{ "ctLOKDMP",		CTPF_NONE },
{ "RWTPREC",		CTPF_HASDATNO },
{ "ADDVREC",		CTPF_HASDATNO },
{ "RWTVREC",		CTPF_HASDATNO },
{ "REDVREC",		CTPF_HASDATNO },
{ "DELRES",		CTPF_HASDATNO },
{ "ENARES",		CTPF_HASDATNO },
{ "UPDRES",		CTPF_HASDATNO },
{ "ADDRES",		CTPF_HASDATNO },
{ "PUTCRES",		CTPF_HASDATNO },
{ "?? 128 ??",		CTPF_NONE },
{ "PTADMIN",		CTPF_HASDATNO },
{ "ADDKEY",		CTPF_HASKEYNO },
{ "LOADKEY",		CTPF_HASKEYNO },
{ "DELCHK",		CTPF_HASKEYNO },
{ "FREBATN",		CTPF_NONE },
{ "FRESETN",		CTPF_NONE },
{ "FREHSTN",		CTPF_NONE },
{ "SETOPS",		CTPF_NONE },
{ "FRERNG",		CTPF_HASKEYNO },
{ "FRSRNG",		CTPF_HASKEYNO },
{ "FRSVRNG",		CTPF_HASKEYNO },
{ "CREDAT",		CTPF_HASCREBLK },
{ "CREIDX",		CTPF_HASCREBLK },
{ "CREMEM",		CTPF_HASKEYNO },
{ "ctDROPIDX",		CTPF_HASKEYNO },
{ "LSTRNG",		CTPF_HASKEYNO },
{ "LSTVRNG",		CTPF_HASKEYNO },
{ "NXTRNG",		CTPF_HASKEYNO },
{ "NXTVRNG",		CTPF_HASKEYNO },
{ "PRVRNG",		CTPF_HASKEYNO },
{ "PRVVRNG",		CTPF_HASKEYNO },
{ "GTEKEY",		CTPF_HASKEYNO },
{ "GTKEY",		CTPF_HASKEYNO },
{ "LTKEY",		CTPF_HASKEYNO },
{ "LTEKEY",		CTPF_HASKEYNO },
{ "DELBLD",		CTPF_HASKEYNO },
{ "EQLKEY",		CTPF_HASKEYNO },
{ "FRSKEY",		CTPF_HASKEYNO },
{ "LSTKEY",		CTPF_HASKEYNO },
{ "GETCURP",		CTPF_HASDATNO },
{ "NEWREC",		CTPF_HASDATNO },
{ "DATENT",		CTPF_HASDATNO },
{ "IDXENT",		CTPF_HASKEYNO },
{ "SERIALNUM",		CTPF_HASDATNO },
{ "TRANBEG",		CTPF_NONE },
{ "NXTKEY",		CTPF_HASKEYNO },
{ "PRVKEY",		CTPF_HASKEYNO },
{ "GETRES",		CTPF_HASDATNO },
{ "CTDIDX",		CTPF_NONE },
{ "ctDISTINCTest",	CTPF_HASKEYNO },
{ "CTUSER",		CTPF_NONE },
{ "GETFIL",		CTPF_HASFILNO },
{ "SEPLNG",		CTPF_HASSEPLNG },
{ "CTUSERX",		CTPF_NONE },
{ "CTSQLCTL",		CTPF_NONE },
{ "CTSRVCTL",		CTPF_NONE },
{ "ctDISTINCTset",	CTPF_HASFILNO },
{ "CTUSERX",		CTPF_NONE },
{ "ctImpersonateTask",	CTPF_NONE },
{ "autoTRANEND",		CTPF_NONE },
{ "?? 179 ??",		CTPF_NONE },
{ "GTVLEN",		CTPF_HASDATNO },
{ "GETVLEN",		CTPF_HASDATNO },
{ "GETIFILX",		CTPF_HASDATNO },
{ "GETDODAX",		CTPF_HASDATNO },
{ "GETCRES",		CTPF_HASDATNO },
{ "GETCIDX",		CTPF_HASKEYNO },
{ "?? 186 ??",		CTPF_NONE },
{ "NOTSENT",		CTPF_NONE },
{ "TFRMKEY",		CTPF_HASKEYNO },
{ "GETCURK",		CTPF_HASKEYNO },
{ "GETCURKL",		CTPF_HASKEYNO },
{ "BATSETX",		CTPF_HASFILNO },
{ "CTSBLDX",		CTPF_HASOPENBLK },
{ "TSTVREC",		CTPF_HASDATNO },
{ "COMMBUF",		CTPF_NONE },
{ "SQR",		CTPF_NONE },
{ "OPNRFIL",		CTPF_HASOPENBLK },
{ "TMPNAME",		CTPF_NONE },
{ "RTG",		CTPF_NONE },
{ "DYNDMP",		CTPF_NONE },
{ "FRCKEY",		CTPF_HASKEYNO },
{ "AVLFILNUM",		CTPF_NONE },
{ "OPNFIL",		CTPF_HASOPENBLK },
{ "BATSET",		CTPF_HASFILNO },
{ "LOKREC",		CTPF_HASDATNO },
{ "ESTKEY",		CTPF_HASKEYNO },
{ "NEWVREC",		CTPF_HASDATNO },
{ "TRANSAV",		CTPF_NONE },
{ "TRANBAK",		CTPF_NONE },
{ "SETFNDVAL",		CTPF_NONE },
{ "IOPERFORMANCE",	CTPF_NONE },
{ "CLNIDXX",		CTPF_HASOPENBLK },
{ "RNGENT",		CTPF_HASKEYNO },
{ "ORDKEY",		CTPF_HASKEYNO },
{ "OPNICON",		CTPF_HASDATNO },
{ "SYSCFG",		CTPF_NONE },
{ "PUTHDR",		CTPF_HASFILNO },
{ "CUST_LOGON",		CTPF_NONE },
{ "CUST_LOGOFF",	CTPF_NONE },
{ "CUST_OPC1",		CTPF_NONE },
{ "CUST_OPC2",		CTPF_NONE },
{ "CUST_OPC3",		CTPF_NONE },
{ "CUST_OPC4",		CTPF_NONE },
{ "CTHIST",		CTPF_HASFILNO },
{ "IOPERFORMANCEX",	CTPF_NONE },
{ "REDIVREC",		CTPF_HASDATNO },
{ "reset_cur2",		CTPF_NONE },
{ "RTSCRIPT",		CTPF_NONE },
{ "ctSETENCRYPT",	CTPF_NONE },
{ "SESSVAL",		CTPF_NONE },
{ "SESSINC",		CTPF_NONE },
{ "SPCLSAV",		CTPF_NONE },
{ "NOFUNCT",		CTPF_NONE },	/* 232 */
{ "NOFUNCT",		CTPF_NONE },	/* 233 */
{ "NOFUNCT",		CTPF_NONE },	/* 234 */
{ "NOFUNCT",		CTPF_NONE },	/* 235 */
{ "NOFUNCT",		CTPF_NONE },	/* 236 */
{ "NOFUNCT",		CTPF_NONE },	/* 237 */
{ "RTG_MAKE",		CTPF_NONE },	/* 238 */
{ "RTG_OPEN",		CTPF_NONE },	/* 239 */
{ "RTG_CLOSE",		CTPF_NONE },	/* 240 */
{ "RTG_WRITE",		CTPF_NONE },	/* 241 */
{ "RTG_READ",		CTPF_NONE },	/* 242 */
{ "RTG_START",		CTPF_NONE },	/* 243 */
{ "RTG_NEXTPREV",	CTPF_NONE },	/* 244 */
{ "RTG_REWDEL",		CTPF_NONE },	/* 245 */
{ "RTG_DELETE",		CTPF_NONE },	/* 246 */
{ "RTG_UNLOCK",		CTPF_NONE },	/* 247 */
{ "RTG_VERSION",	CTPF_NONE },	/* 248 */
{ "RTG_SQLINFO",	CTPF_NONE },	/* 249 */
{ "RTG_SQLLINK",	CTPF_NONE },	/* 250 */
{ "RTG_COPY",		CTPF_NONE },	/* 251 */
{ "RTG_INFO",		CTPF_NONE },	/* 252 */
{ "RTG_ADDIDX",		CTPF_NONE },	/* 253 */
{ "RTG_REMOVE",		CTPF_NONE },	/* 254 */
{ "RTG_RENAME",		CTPF_NONE } 	/* 255 */
/* ctSIBLING_RTG: Add new RTG sub-function name here. NOTE: After we reach 255,
** we must add new RTG sub-functions to a different list. */
};

CTPF_FNM ctsepnam[] = { /* SEPLNG sub-function support */
{ "NOFUNCSEP",		CTPF_NONE },
{ "PUTKSEGDEF",		CTPF_HASFILNO },
{ "GETKSEGDEF",		CTPF_HASFILNO },
{ "XFMKSEGDEF",		CTPF_NONE },
{ "ctunic",		CTPF_HASFILNO },
{ "GETXCREBLK",		CTPF_HASFILNO },
{ "CTFLUSHX",		CTPF_HASFILNO },
{ "CTASYNC",		CTPF_NONE },
{ "ctksegswpchk",	CTPF_HASFILNO },
{ "ctSNAPSHOT",		CTPF_NONE },
{ "ctSYSPUT",		CTPF_NONE },
{ "ctCLSNAM",		CTPF_HASNAME },
{ "ctSysQueueOpen",	CTPF_NONE },
{ "ctSysQueueClose",	CTPF_NONE },
{ "ctSysQueueWrite",	CTPF_NONE },
{ "ctSysQueueLIFOWrite",CTPF_NONE },
{ "ctSysQueueRead",	CTPF_NONE },
{ "ctSysQueueMlen",	CTPF_NONE },
{ "ctSysQueueCount",	CTPF_NONE },
{ "ctNotify",		CTPF_NONE },
{ "ALCRNG",		CTPF_HASFILNO },
{ "BLKIREC",		CTPF_HASFILNO },
{ "TRANUSR",		CTPF_NONE },
{ "ctReplSetPosByLogPos", CTPF_NONE },
{ "ctReplSetPosByTime", CTPF_NONE },
{ "ctReplGetFileName",  CTPF_NONE },
{ "ctReplGetNextChange", CTPF_NONE },
{ "ctReplPersistMinLog", CTPF_NONE },
{ "SETCBRBL",		CTPF_NONE },
{ "ctFILMTX",		CTPF_NONE },
{ "ctLOKLST",		CTPF_HASFILNO },
{ "ctFILBLK",		CTPF_NONE },
{ "ctSETCFG",		CTPF_NONE },
{ "ctFILWCD",		CTPF_NONE },
{ "ctQUIET",		CTPF_NONE },
{ "ctLOKTIMOUT",	CTPF_NONE },
{ "ctUPDTICU",		CTPF_HASNAME },
{ "ctGetOpenFiles",	CTPF_NONE },
{ "ctGetFileUsers",	CTPF_NONE },
{ "ctGetFileLocks",	CTPF_NONE },
{ "ctLOKDYN",		CTPF_NONE },
{ "ctReplAgentOp",	CTPF_NONE },
{ "ctTransferFile",	CTPF_NONE },
{ "ESTRNG",		CTPF_HASFILNO },
{ "ctSEQUENCE",		CTPF_NONE },
{ "ctMASTERCTL",	CTPF_NONE },
{ "ctDISTINCTestXtd",	CTPF_HASKEYNO },
{ "ctDISTINCTsetXtd",	CTPF_HASFILNO },
{ "ctVERIFYidx",	CTPF_NONE },
{ "addIDfield",		CTPF_HASFILNO },
{ "delIDfield",		CTPF_HASFILNO },
{ "getIDfield",		CTPF_HASFILNO },
{ "resetIDfield",	CTPF_HASFILNO },
{ "wchIDfield",		CTPF_HASFILNO },
{ "ctMEMSTAT",		CTPF_NONE },
{ "ctSETCOMPRESS",	CTPF_NONE },
{ "xtdatrIDfield",	CTPF_HASFILNO },
{ "ctCopyFile",		CTPF_NONE },
{ "ctVerifyFile",	CTPF_NONE },
{ "GETFILX",		CTPF_HASFILNO },
{ "ctDeferredIndexControl", CTPF_NONE },
{ "ctRecordUpdateCallbackControl", CTPF_NONE },
{ "ctReplSetFileFilter", CTPF_NONE },
{ "ctFullText",		CTPF_NONE },
{ "ctAlterSchema",	CTPF_HASFILNO },
{ "ctReplCheckFileFilter", CTPF_NONE },
{ "ctTempDir",		CTPF_NONE },
{ "ctReplLogFileResync",CTPF_NONE },
{ "ctGetAccountExpirationTime",CTPF_NONE },
{ "ctGetConnectionInfo",CTPF_NONE },
{ "UpdateRecordOffsetForKey",CTPF_NONE },
{ "USERINFOX",		CTPF_NONE },
{ "ctSyncReplControl",	CTPF_NONE },
{ "addAutoSysTimeFields",		CTPF_HASFILNO },
{ "RemoveAutoSysTimeFields",		CTPF_HASFILNO },
{ "WhichAutoSysTimeFields",		CTPF_HASFILNO },
{ "UpdateAutoSysTimeFields",		CTPF_HASFILNO },
{ "GetFileRegions",	CTPF_HASFILNO },
{ "ctGetOpenFilesXtd",	CTPF_NONE },
{ "ctReplSetPosByTransactionId",	CTPF_NONE },
{ "ctFILELIST",		CTPF_NONE },
{ "ctReplReadLogData",	CTPF_NONE },
{ "replagentfunction",	CTPF_NONE },
{ "ctReplCleanupTranStateKeys",	CTPF_NONE },
{ "ctClusterConfig",	CTPF_NONE },
{ "ctTruncateFile",	CTPF_NONE },
{ "ctReplGetPosForTransactionId",	CTPF_NONE },
{ "ctPlugin",	CTPF_NONE },
{ "DELFILX",	CTPF_NONE },
{ "DELIFILX",	CTPF_NONE },
{ "DELRFILX",	CTPF_NONE },
{ "ctSetNullKeyValue",	CTPF_HASKEYNO },
{ "ctGetNullKeyValue",	CTPF_HASKEYNO },
{ "ctGetRecordConverters",	CTPF_HASFILNO },
{ "addChangeIDfield", CTPF_HASFILNO },
{ "getChangeIDfieldNumber", CTPF_HASFILNO },
{ "delChangeIDfield", CTPF_HASFILNO },
{ "getChangeIDheaderValue", CTPF_HASFILNO },
{ "ctSetConnectionAttribute", CTPF_NONE },
{ "ctFILBLKX", CTPF_NONE },
{ "ctNextSequenceUniqueName", CTPF_NONE },
{ "ctCreateUUID", CTPF_NONE },
{ "ctSetDatabaseEngineUUID", CTPF_NONE },
{ "ctGetDatabaseEngineUUID", CTPF_NONE },
/* ctSIBLING_SEPLNG: Add entry for new function here */

{ "NOFUNCSEP",		CTPF_NONE }
};

typedef TEXT checkSepnamInitializers[sizeof(ctsepnam) / sizeof(*ctsepnam) == ctSEPLNGlimit + 1];
#endif

/* end ctpfnm.h */
