/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iscobol_intf_Ctree */

#ifndef _Included_com_iscobol_intf_Ctree
#define _Included_com_iscobol_intf_Ctree
#ifdef __cplusplus
extern "C" {
#endif
#undef com_iscobol_intf_Ctree_Finput
#define com_iscobol_intf_Ctree_Finput 0L
#undef com_iscobol_intf_Ctree_Foutput
#define com_iscobol_intf_Ctree_Foutput 1L
#undef com_iscobol_intf_Ctree_Fio
#define com_iscobol_intf_Ctree_Fio 2L
#undef com_iscobol_intf_Ctree_Fextend
#define com_iscobol_intf_Ctree_Fextend 3L
#undef com_iscobol_intf_Ctree_Fopen_mask
#define com_iscobol_intf_Ctree_Fopen_mask 3L
#undef com_iscobol_intf_Ctree_Ftext
#define com_iscobol_intf_Ctree_Ftext 4L
#undef com_iscobol_intf_Ctree_Fbinary
#define com_iscobol_intf_Ctree_Fbinary 0L
#undef com_iscobol_intf_Ctree_Flocal_only
#define com_iscobol_intf_Ctree_Flocal_only 8L
#undef com_iscobol_intf_Ctree_Fmulti_lock
#define com_iscobol_intf_Ctree_Fmulti_lock 16L
#undef com_iscobol_intf_Ctree_Fmulti_records
#define com_iscobol_intf_Ctree_Fmulti_records 32L
#undef com_iscobol_intf_Ctree_Ftruncate
#define com_iscobol_intf_Ctree_Ftruncate 64L
#undef com_iscobol_intf_Ctree_Fread_lock
#define com_iscobol_intf_Ctree_Fread_lock 256L
#undef com_iscobol_intf_Ctree_Fwrite_lock
#define com_iscobol_intf_Ctree_Fwrite_lock 512L
#undef com_iscobol_intf_Ctree_Fbuffered
#define com_iscobol_intf_Ctree_Fbuffered 1024L
#undef com_iscobol_intf_Ctree_Fmass_update
#define com_iscobol_intf_Ctree_Fmass_update 1536L
#undef com_iscobol_intf_Ctree_Flock_mask
#define com_iscobol_intf_Ctree_Flock_mask 1792L
#undef com_iscobol_intf_Ctree_Fis_device
#define com_iscobol_intf_Ctree_Fis_device 2048L
#undef com_iscobol_intf_Ctree_Fopt_lock
#define com_iscobol_intf_Ctree_Fopt_lock 4096L
#undef com_iscobol_intf_Ctree_Fappend
#define com_iscobol_intf_Ctree_Fappend 8192L
#undef com_iscobol_intf_Ctree_Ftrans
#define com_iscobol_intf_Ctree_Ftrans 16384L
#undef com_iscobol_intf_Ctree_F_EQUALS
#define com_iscobol_intf_Ctree_F_EQUALS 0L
#undef com_iscobol_intf_Ctree_F_NOT_LESS
#define com_iscobol_intf_Ctree_F_NOT_LESS 1L
#undef com_iscobol_intf_Ctree_F_GREATER
#define com_iscobol_intf_Ctree_F_GREATER 2L
#undef com_iscobol_intf_Ctree_F_LESS
#define com_iscobol_intf_Ctree_F_LESS 3L
#undef com_iscobol_intf_Ctree_F_NOT_GREATER
#define com_iscobol_intf_Ctree_F_NOT_GREATER 4L
#undef com_iscobol_intf_Ctree_E_SYS_ERR
#define com_iscobol_intf_Ctree_E_SYS_ERR 1L
#undef com_iscobol_intf_Ctree_E_PARAM_ERR
#define com_iscobol_intf_Ctree_E_PARAM_ERR 2L
#undef com_iscobol_intf_Ctree_E_TOO_MANY_FILES
#define com_iscobol_intf_Ctree_E_TOO_MANY_FILES 3L
#undef com_iscobol_intf_Ctree_E_MODE_CLASH
#define com_iscobol_intf_Ctree_E_MODE_CLASH 4L
#undef com_iscobol_intf_Ctree_E_REC_LOCKED
#define com_iscobol_intf_Ctree_E_REC_LOCKED 5L
#undef com_iscobol_intf_Ctree_E_BROKEN
#define com_iscobol_intf_Ctree_E_BROKEN 6L
#undef com_iscobol_intf_Ctree_E_DUPLICATE
#define com_iscobol_intf_Ctree_E_DUPLICATE 7L
#undef com_iscobol_intf_Ctree_E_NOT_FOUND
#define com_iscobol_intf_Ctree_E_NOT_FOUND 8L
#undef com_iscobol_intf_Ctree_E_UNDEF_RECORD
#define com_iscobol_intf_Ctree_E_UNDEF_RECORD 9L
#undef com_iscobol_intf_Ctree_E_DISK_FULL
#define com_iscobol_intf_Ctree_E_DISK_FULL 10L
#undef com_iscobol_intf_Ctree_E_FILE_LOCKED
#define com_iscobol_intf_Ctree_E_FILE_LOCKED 11L
#undef com_iscobol_intf_Ctree_E_REC_CHANGED
#define com_iscobol_intf_Ctree_E_REC_CHANGED 12L
#undef com_iscobol_intf_Ctree_E_MISMATCH
#define com_iscobol_intf_Ctree_E_MISMATCH 13L
#undef com_iscobol_intf_Ctree_E_NO_MEMORY
#define com_iscobol_intf_Ctree_E_NO_MEMORY 14L
#undef com_iscobol_intf_Ctree_E_MISSING_FILE
#define com_iscobol_intf_Ctree_E_MISSING_FILE 15L
#undef com_iscobol_intf_Ctree_E_PERMISSION
#define com_iscobol_intf_Ctree_E_PERMISSION 16L
#undef com_iscobol_intf_Ctree_E_NO_SUPPORT
#define com_iscobol_intf_Ctree_E_NO_SUPPORT 17L
#undef com_iscobol_intf_Ctree_E_NO_LOCKS
#define com_iscobol_intf_Ctree_E_NO_LOCKS 18L
#undef com_iscobol_intf_Ctree_E_INTERFACE
#define com_iscobol_intf_Ctree_E_INTERFACE 19L
#undef com_iscobol_intf_Ctree_E_LICENSE_ERR
#define com_iscobol_intf_Ctree_E_LICENSE_ERR 20L
#undef com_iscobol_intf_Ctree_E_UNKNOWN_ERR
#define com_iscobol_intf_Ctree_E_UNKNOWN_ERR 21L
#undef com_iscobol_intf_Ctree_E_TRANSACTION
#define com_iscobol_intf_Ctree_E_TRANSACTION 22L
#undef com_iscobol_intf_Ctree_W_NO_SUPPORT
#define com_iscobol_intf_Ctree_W_NO_SUPPORT 100L
#undef com_iscobol_intf_Ctree_W_DUP_OK
#define com_iscobol_intf_Ctree_W_DUP_OK 101L
/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_iscobol_intf_Ctree_ct_1init
  (JNIEnv *, jclass);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_init2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_iscobol_intf_Ctree_ct_1init2
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_init_cfg
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_iscobol_intf_Ctree_ct_1init_1cfg
  (JNIEnv *, jclass);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_exit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_iscobol_intf_Ctree_ct_1exit
  (JNIEnv *, jclass);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_exit2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_iscobol_intf_Ctree_ct_1exit2
  (JNIEnv *, jclass);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_make
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[B)I
 */
JNIEXPORT jint JNICALL Java_com_iscobol_intf_Ctree_ct_1make
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jbyteArray);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_make2
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[BB)I
 */
JNIEXPORT jint JNICALL Java_com_iscobol_intf_Ctree_ct_1make2
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jbyteArray, jbyte);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_open
 * Signature: (Ljava/lang/String;ILjava/lang/String;I)I
 */
JNIEXPORT jlong JNICALL Java_com_iscobol_intf_Ctree_ct_1open
  (JNIEnv *, jclass, jstring, jint, jstring, jint);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_open2
 * Signature: (Ljava/lang/String;ILjava/lang/String;B)I
 */
JNIEXPORT jlong JNICALL Java_com_iscobol_intf_Ctree_ct_1open2
  (JNIEnv *, jclass, jstring, jint, jstring, jbyte);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_iscobol_intf_Ctree_ct_1close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_lockwait
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_iscobol_intf_Ctree_ct_1lockwait
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_sqlinfo
 * Signature: (ILjava/lang/String;B)I
 */
JNIEXPORT jint JNICALL Java_com_iscobol_intf_Ctree_ct_1sqlinfo
  (JNIEnv *, jclass, jlong, jstring, jbyte);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_sqllink
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_iscobol_intf_Ctree_ct_1sqllink
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_sqlunlink
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_iscobol_intf_Ctree_ct_1sqlunlink
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_read
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_com_iscobol_intf_Ctree_ct_1read
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_next
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_iscobol_intf_Ctree_ct_1next
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_previous
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_iscobol_intf_Ctree_ct_1previous
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_start
 * Signature: (I[BIIII)I
 */
JNIEXPORT jint JNICALL Java_com_iscobol_intf_Ctree_ct_1start
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jint, jint);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_write
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_com_iscobol_intf_Ctree_ct_1write
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_rewrite
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_com_iscobol_intf_Ctree_ct_1rewrite
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_delete
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_iscobol_intf_Ctree_ct_1delete
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_unlock
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_iscobol_intf_Ctree_ct_1unlock
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_info
 * Signature: (II[B)I
 */
JNIEXPORT jint JNICALL Java_com_iscobol_intf_Ctree_ct_1info
  (JNIEnv *, jclass, jlong, jint, jbyteArray);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_sync
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_iscobol_intf_Ctree_ct_1sync
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_remove
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_iscobol_intf_Ctree_ct_1remove
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_rename
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_iscobol_intf_Ctree_ct_1rename
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_version
 * Signature: ([B[B[BI[I)I
 */
JNIEXPORT jint JNICALL Java_com_iscobol_intf_Ctree_ct_1version
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jint, jintArray);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_abilities
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_iscobol_intf_Ctree_ct_1abilities
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_execute
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_iscobol_intf_Ctree_ct_1execute
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_copy
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_iscobol_intf_Ctree_ct_1copy
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_begin
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_iscobol_intf_Ctree_ct_1begin
  (JNIEnv *, jclass);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_commit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_iscobol_intf_Ctree_ct_1commit
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_rollback
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_iscobol_intf_Ctree_ct_1rollback
  (JNIEnv *, jclass);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_recover
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_iscobol_intf_Ctree_ct_1recover
  (JNIEnv *, jclass);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    get_f_errno
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_com_iscobol_intf_Ctree_get_1f_1errno
  (JNIEnv *, jclass);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    get_f_int_errno
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_iscobol_intf_Ctree_get_1f_1int_1errno
  (JNIEnv *, jclass);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    get_f_int2_errno
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_iscobol_intf_Ctree_get_1f_1int2_1errno
  (JNIEnv *, jclass);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    get_f_no_lock
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_com_iscobol_intf_Ctree_get_1f_1no_1lock
  (JNIEnv *, jclass);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    get_f_errmsg
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_iscobol_intf_Ctree_get_1f_1errmsg
  (JNIEnv *, jclass);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    get_i_implied_transaction
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_com_iscobol_intf_Ctree_get_1i_1implied_1transaction
  (JNIEnv *, jclass);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    get_i_in_commit
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_com_iscobol_intf_Ctree_get_1i_1in_1commit
  (JNIEnv *, jclass);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    get_i_in_transaction
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_com_iscobol_intf_Ctree_get_1i_1in_1transaction
  (JNIEnv *, jclass);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    set_f_errno
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_com_iscobol_intf_Ctree_set_1f_1errno
  (JNIEnv *, jclass, jshort);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    set_f_int_errno
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_iscobol_intf_Ctree_set_1f_1int_1errno
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    set_f_int2_errno
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_iscobol_intf_Ctree_set_1f_1int2_1errno
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    set_f_no_lock
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_com_iscobol_intf_Ctree_set_1f_1no_1lock
  (JNIEnv *, jclass, jshort);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    set_f_errmsg
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_iscobol_intf_Ctree_set_1f_1errmsg
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    set_i_implied_transaction
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_com_iscobol_intf_Ctree_set_1i_1implied_1transaction
  (JNIEnv *, jclass, jshort);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    set_i_in_commit
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_com_iscobol_intf_Ctree_set_1i_1in_1commit
  (JNIEnv *, jclass, jshort);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    set_i_in_transaction
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_com_iscobol_intf_Ctree_set_1i_1in_1transaction
  (JNIEnv *, jclass, jshort);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_exitsrv
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_iscobol_intf_Ctree_ct_1exitsrv
  (JNIEnv *, jclass);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_initsrv
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_iscobol_intf_Ctree_ct_1initsrv
  (JNIEnv *, jclass);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_attach
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_iscobol_intf_Ctree_ct_1attach
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_threadid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_iscobol_intf_Ctree_ct_1threadid
  (JNIEnv *, jclass);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_detach
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_iscobol_intf_Ctree_ct_1detach
  (JNIEnv *, jclass);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_config
 * Signature: (ILLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)L
 */
JNIEXPORT jlong JNICALL Java_com_iscobol_intf_Ctree_ct_1config
  (JNIEnv *, jclass, jint, jlong, jlong, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_lockerid
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_iscobol_intf_Ctree_ct_1lockerid
  (JNIEnv *, jclass );

  /*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_logons
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_iscobol_intf_Ctree_ct_1logons
  (JNIEnv *, jclass );


#ifdef NOT_YET /* MB140701 waiting for Veryant */
/*
 * Class:     com_iscobol_intf_Ctree
 * Method:    ct_configxml
 * Signature: (L[BL)L
 */
JNIEXPORT jlong JNICALL Java_com_iscobol_intf_Ctree_ct_1configxml
  (JNIEnv *, jclass, jlong, jbyteArray, jlong);
#endif

#ifdef __cplusplus
}
#endif
#endif
