/*
 *      OFFICIAL NOTIFICATION: the following CONFIDENTIAL and PROPRIETARY
 * 	property legend shall not be removed from this source code module
 * 	for any reason.
 *
 *	This program is the CONFIDENTIAL and PROPRIETARY property
 *	of FairCom(R) Corporation. Any unauthorized use, reproduction or
 *	transfer of this computer program is strictly prohibited. The
 *      contents of this file may not be disclosed to third parties, copied or
 *      duplicated in any form, in whole or in part, without the prior written
 *      permission of the FairCom(R) Corporation.
 *
 *      Copyright (c) 1992 - 2024 FairCom Corporation.
 *	This is an unpublished work, and is subject to limited distribution and
 *	restricted disclosure only. ALL RIGHTS RESERVED.
 *
 *			RESTRICTED RIGHTS LEGEND
 *	Use, duplication, or disclosure by the Government is subject to
 *	restrictions set forth in subparagraph (c)(1)(ii) of the Rights in
 * 	Technical Data and Computer Software clause at DFARS 252.227-7013, and/or
 *      in similar or successor clauses in the FAR, DOD or NASA FAR Supplement.
 *      Unpublished rights reserved under the Copyright Laws of the United States.
 *	FairCom Corporation, 6300 West Sugar Creek Drive, Columbia, MO 65203.
 *
 *	c-treeACE(tm)	Version 13
 */

#ifdef	CTDBCEPTLAYER	/* If intercept layer defined */

#define ctdbDayOfWeek				ii_ctdbDayOfWeek
#define _ctdbGetDatno				ii_ctdbGetDatno
#define ctdbGetDay				ii_ctdbGetDay
#define ctdbGetHour				ii_ctdbGetHour
#define ctdbGetMinute				ii_ctdbGetMinute
#define ctdbGetMonth				ii_ctdbGetMonth
#define ctdbGetSecond				ii_ctdbGetSecond
#define ctdbGetYear				ii_ctdbGetYear
#define ctdbGetFieldNullFlag			ii_ctdbGetFieldNullFlag
#define ctdbGetIndexDuplicateFlag		ii_ctdbGetIndexDuplicateFlag
#define ctdbGetIndexNullFlag			ii_ctdbGetIndexNullFlag
#define ctdbGetIndexTemporaryFlag		ii_ctdbGetIndexTemporaryFlag
#define ctdbGetLockActive			ii_ctdbGetLockActive
#define ctdbGetLogonOnly			ii_ctdbGetLogonOnly
#define ctdbHasNullFieldSupport			ii_ctdbHasNullFieldSupport
#define ctdbIsActiveDatabase			ii_ctdbIsActiveDatabase
#define ctdbIsActiveSession			ii_ctdbIsActiveSession
#define ctdbIsActiveTable			ii_ctdbIsActiveTable
#define ctdbIsEditedRecord			ii_ctdbIsEditedRecord
#define ctdbIsExtSegment			ii_ctdbIsExtSegment
#define ctdbIsLeapYear				ii_ctdbIsLeapYear
#define ctdbIsLockActive			ii_ctdbIsLockActive
#define ctdbIsNewRecord				ii_ctdbIsNewRecord
#define ctdbIsNullField				ii_ctdbIsNullField
#define ctdbIsTransActive			ii_ctdbIsTransActive
#define ctdbIsVariableField			ii_ctdbIsVariableField
#define _ctdbSuperIsExclusive			ii_ctdbSuperIsExclusive
#define _ctdbSuperIsOpen				ii_ctdbSuperIsOpen
#define _ctdbTestBit				ii_ctdbTestBit
#define ctdbGetTableCreateMode			ii_ctdbGetTableCreateMode
#define ctdbGetDefDateType			ii_ctdbGetDefDateType
#define ctdbGetIndexKeyType			ii_ctdbGetIndexKeyType
#define _ctdbGetNumberOfIndexEntries		ii_ctdbGetNumberOfIndexEntries
#define _ctdbGetNumberOfRecords			ii_ctdbGetNumberOfRecords
#define _ctdbADDREC				ii_ctdbADDREC
#define _ctdbADDRES				ii_ctdbADDRES
#define _ctdbADDVREC				ii_ctdbADDVREC
#define _ctdbAVLFILNBR				ii_ctdbAVLFILNBR
#define ctdbAbort				ii_ctdbAbort
#define ctdbAddDatabase				ii_ctdbAddDatabase
#define ctdbAddLock				ii_ctdbAddLock
#define ctdbAddTable				ii_ctdbAddTable
#define ctdbAddTableXtd				ii_ctdbAddTableXtd
#define ctdbAlterTable				ii_ctdbAlterTable
#define ctdbBegin				ii_ctdbBegin
#define ctdbPrepareCommit			ii_ctdbPrepareCommit
#define ctdbBlobClear				ii_ctdbBlobClear
#define ctdbBlobSet				ii_ctdbBlobSet
#define ctdbBuildTargetKey			ii_ctdbBuildTargetKey
#define _ctdbCHGICON				ii_ctdbCHGICON
#define _ctdbCLRFIL				ii_ctdbCLRFIL
#define _ctdbCLSFIL				ii_ctdbCLSFIL
#define _ctdbCLSICON				ii_ctdbCLSICON
#define _ctdbCREDAT				ii_ctdbCREDAT
#define _ctdbCREIFILX				ii_ctdbCREIFILX
#define _ctdbCREIFILXX				ii_ctdbCREIFILXX
#define _ctdbClearDict				ii_ctdbClearDict
#define ctdbClearField				ii_ctdbClearField
#define ctdbClearRecord				ii_ctdbClearRecord
#define ctdbClearTableSuperFile			ii_ctdbClearTableSuperFile
#define ctdbCloseAll				ii_ctdbCloseAll
#define _ctdbCloseDict				ii_ctdbCloseDict
#define ctdbCloseTable				ii_ctdbCloseTable
#define ctdbCommit				ii_ctdbCommit
#define ctdbConnect				ii_ctdbConnect
#define ctdbCopyRecordBuffer			ii_ctdbCopyRecordBuffer
#define ctdbCreateDatabase			ii_ctdbCreateDatabase
#define _ctdbCreateDict				ii_ctdbCreateDict
#define ctdbCreateSession			ii_ctdbCreateSession
#define ctdbCreateTable				ii_ctdbCreateTable
#define ctdbCurrentDate				ii_ctdbCurrentDate
#define ctdbCurrentDateTime			ii_ctdbCurrentDateTime
#define ctdbCurrentTime				ii_ctdbCurrentTime
#define ctdbServerDateTime			ii_ctdbServerDateTime
#define _ctdbDELFIL				ii_ctdbDELFIL
#define _ctdbDELREC				ii_ctdbDELREC
#define _ctdbDELRFIL				ii_ctdbDELRFIL
#define _ctdbDELVREC				ii_ctdbDELVREC
#define ctdbDateCheck				ii_ctdbDateCheck
#define ctdbDatePack				ii_ctdbDatePack
#define ctdbDateTimeGetDate			ii_ctdbDateTimeGetDate
#define ctdbDateTimeGetTime			ii_ctdbDateTimeGetTime
#define ctdbDateTimePack			ii_ctdbDateTimePack
#define ctdbDateTimeSetDate			ii_ctdbDateTimeSetDate
#define ctdbDateTimeSetTime			ii_ctdbDateTimeSetTime
#define ctdbDateTimeToString			ii_ctdbDateTimeToString
#define ctdbDateTimeUnpack			ii_ctdbDateTimeUnpack
#define ctdbDateToString			ii_ctdbDateToString
#define ctdbDateUnpack				ii_ctdbDateUnpack
#define ctdbDelField				ii_ctdbDelField
#define ctdbDelFieldByName			ii_ctdbDelFieldByName
#define ctdbDelIndex				ii_ctdbDelIndex
#define ctdbDelLock				ii_ctdbDelLock
#define ctdbDelSegment				ii_ctdbDelSegment
#define ctdbDelSegmentEx			ii_ctdbDelSegmentEx
#define ctdbDeleteDatabase			ii_ctdbDeleteDatabase
#define _ctdbDeleteDict				ii_ctdbDeleteDict
#define ctdbDeleteRecord			ii_ctdbDeleteRecord
#define ctdbDeleteTable				ii_ctdbDeleteTable
#define _ctdbDictAddAllIndex			ii_ctdbDictAddAllIndex
#define _ctdbDictAddDatabase			ii_ctdbDictAddDatabase
#define _ctdbDictAddIndex			ii_ctdbDictAddIndex
#define _ctdbDictAddTable			ii_ctdbDictAddTable
#define _ctdbDictDropAllIndex			ii_ctdbDictDropAllIndex
#define _ctdbDictDropDatabase			ii_ctdbDictDropDatabase
#define _ctdbDictDropIndex			ii_ctdbDictDropIndex
#define _ctdbDictDropTable			ii_ctdbDictDropTable
#define _ctdbDictFindDatabase			ii_ctdbDictFindDatabase
#define _ctdbDictFindDatabaseByUID		ii_ctdbDictFindDatabaseByUID
#define _ctdbDictFindIndex			ii_ctdbDictFindIndex
#define _ctdbDictFindIndexByUID			ii_ctdbDictFindIndexByUID
#define _ctdbDictFindTable			ii_ctdbDictFindTable
#define _ctdbDictFindTableByUID			ii_ctdbDictFindTableByUID
#define _ctdbDictFirstDatabase			ii_ctdbDictFirstDatabase
#define _ctdbDictFirstTable			ii_ctdbDictFirstTable
#define _ctdbDictGetDatabaseUID			ii_ctdbDictGetDatabaseUID
#define _ctdbDictGetTableUID			ii_ctdbDictGetTableUID
#define _ctdbDictNextDatabase			ii_ctdbDictNextDatabase
#define _ctdbDictNextTable			ii_ctdbDictNextTable
#define _ctdbDictReserveIndex			ii_ctdbDictReserveIndex
#define _ctdbDictReserveTable			ii_ctdbDictReserveTable
#define _ctdbDictUpdateIndex			ii_ctdbDictUpdateIndex
#define ctdbDisconnect				ii_ctdbDisconnect
#define ctdbDisconnectAll			ii_ctdbDisconnectAll
#define ctdbDropDatabase			ii_ctdbDropDatabase
#define ctdbDropTable				ii_ctdbDropTable
#define _ctdbDumpDict				ii_ctdbDumpDict
#define _ctdbEndDebug				ii_ctdbEndDebug
#define _ctdbFINDREC				ii_ctdbFINDREC
#define _ctdbFRESET				ii_ctdbFRESET
#define _ctdbFileExist				ii_ctdbFileExist
#define ctdbFindDatabase			ii_ctdbFindDatabase
#define ctdbFindDatabaseByUID			ii_ctdbFindDatabaseByUID
#define _ctdbFindDict				ii_ctdbFindDict
#define _ctdbFindDictByUID			ii_ctdbFindDictByUID
#define ctdbFindRecord				ii_ctdbFindRecord
#define ctdbLocateRecord			ii_ctdbLocateRecord
#define ctdbSetRecordCriteria		ii_ctdbSetRecordCriteria
#define ctdbUpdateRecordCriteria		ii_ctdbUpdateRecordCriteria
#define ctdbGetBestIndex		    ii_ctdbGetBestIndex
#define ctdbAddLocateCriteria		ii_ctdbAddLocateCriteria
#define ctdbFindTable				ii_ctdbFindTable
#define ctdbFindTableByUID			ii_ctdbFindTableByUID
#define ctdbFindTarget				ii_ctdbFindTarget
#define ctdbFirstDatabase			ii_ctdbFirstDatabase
#define _ctdbFirstDict				ii_ctdbFirstDict
#define ctdbFirstRecord				ii_ctdbFirstRecord
#define ctdbFirstTable				ii_ctdbFirstTable
#define ctdbFloatToMoney			ii_ctdbFloatToMoney
#define _ctdbGETCURP				ii_ctdbGETCURP
#define _ctdbGETDODA				ii_ctdbGETDODA
#define _ctdbGETFIL				ii_ctdbGETFIL
#define _ctdbGETIFIL				ii_ctdbGETIFIL
#define _ctdbGETRES				ii_ctdbGETRES
#define _ctdbGETSCHEMA				ii_ctdbGETSCHEMA
#define _ctdbGETVLEN				ii_ctdbGETVLEN
#define ctdbGetActiveDatabaseUID		ii_ctdbGetActiveDatabaseUID
#define ctdbGetActiveTableUID			ii_ctdbGetActiveTableUID
#define ctdbGetDatabaseUID			ii_ctdbGetDatabaseUID
#define _ctdbGetDict				ii_ctdbGetDict
#define _ctdbGetDictUID				ii_ctdbGetDictUID
#define ctdbGetError				ii_ctdbGetError
#define ctdbGetFieldAsBinary			ii_ctdbGetFieldAsBinary
#define ctdbGetFieldAsBlob			ii_ctdbGetFieldAsBlob
#define ctdbGetFieldAsBool			ii_ctdbGetFieldAsBool
#define ctdbGetFieldAsDate			ii_ctdbGetFieldAsDate
#define ctdbGetFieldAsDateTime			ii_ctdbGetFieldAsDateTime
#define ctdbGetFieldAsFloat			ii_ctdbGetFieldAsFloat
#define ctdbGetFieldAsMoney			ii_ctdbGetFieldAsMoney
#define ctdbGetFieldAsSigned			ii_ctdbGetFieldAsSigned
#define ctdbGetFieldAsString			ii_ctdbGetFieldAsString
#define ctdbGetFieldAsTime			ii_ctdbGetFieldAsTime
#define ctdbGetFieldAsUnsigned			ii_ctdbGetFieldAsUnsigned
#define ctdbGetFieldProperties			ii_ctdbGetFieldProperties
#define _ctdbGetFldx				ii_ctdbGetFldx
#define ctdbGetIndexNbr				ii_ctdbGetIndexNbr
#define ctdbGetRecordCount			ii_ctdbGetRecordCount
#define ctdbGetRecordPos			ii_ctdbGetRecordPos
#define ctdbGetRecordKeyPos			ii_ctdbGetRecordKeyPos
#define ctdbGetSegmentNbr			ii_ctdbGetSegmentNbr
#define ctdbGetSessionPath			ii_ctdbGetSessionPath
#define ctdbGetTableUID				ii_ctdbGetTableUID
#define ctdbGetUserTag				ii_ctdbGetUserTag
#define _ctdbIconAdd				ii_ctdbIconAdd
#define _ctdbIconAlloc				ii_ctdbIconAlloc
#define _ctdbIconFree				ii_ctdbIconFree
#define _ctdbIconReset				ii_ctdbIconReset
#define _ctdbIconSwitch				ii_ctdbIconSwitch
#define _ctdbLKISAM				ii_ctdbLKISAM
#define _ctdbLOKREC				ii_ctdbLOKREC
#define ctdbLastRecord				ii_ctdbLastRecord
#define _ctdbListAdd				ii_ctdbListAdd
#define _ctdbListClear				ii_ctdbListClear
#define _ctdbListDelete				ii_ctdbListDelete
#define _ctdbListDeleteEx			ii_ctdbListDeleteEx
#define _ctdbListExchange			ii_ctdbListExchange
#define _ctdbListExpand				ii_ctdbListExpand
#define _ctdbListInsert				ii_ctdbListInsert
#define _ctdbListMove				ii_ctdbListMove
#define _ctdbListReplace				ii_ctdbListReplace
#define _ctdbListSort				ii_ctdbListSort
#define ctdbLock				ii_ctdbLock
#define ctdbLockRecord				ii_ctdbLockRecord
#define ctdbLogon				ii_ctdbLogon
#define ctdbLogout				ii_ctdbLogout
#define ctdbLongToMoney				ii_ctdbLongToMoney
#define _ctdbMOVREC				ii_ctdbMOVREC
#define _ctdbMOVSET				ii_ctdbMOVSET
#define ctdbMoneyAdd				ii_ctdbMoneyAdd
#define ctdbMoneyDiv				ii_ctdbMoneyDiv
#define ctdbMoneyMul				ii_ctdbMoneyMul
#define ctdbMoneySub				ii_ctdbMoneySub
#define ctdbMoneyToFloat			ii_ctdbMoneyToFloat
#define ctdbMoneyToLong				ii_ctdbMoneyToLong
#define ctdbMoneyToString			ii_ctdbMoneyToString
#define ctdbMoveField				ii_ctdbMoveField
#define ctdbNextDatabase			ii_ctdbNextDatabase
#define _ctdbNextDict				ii_ctdbNextDict
#define ctdbNextRecord				ii_ctdbNextRecord
#define ctdbNextTable				ii_ctdbNextTable
#define _ctdbOPNFIL				ii_ctdbOPNFIL
#define _ctdbOPNICON				ii_ctdbOPNICON
#define _ctdbOPNRFILX				ii_ctdbOPNRFILX
#define _ctdbOpenDict				ii_ctdbOpenDict
#define ctdbOpenTable				ii_ctdbOpenTable
#define ctdbOpenTableByUID			ii_ctdbOpenTableByUID
#define _ctdbPRMIIDX				ii_ctdbPRMIIDX
#define _ctdbTMPIIDX				ii_ctdbTMPIIDX
#define ctdbPrevRecord				ii_ctdbPrevRecord
#define _ctdbPutDict				ii_ctdbPutDict
#define _ctdbPutFldx				ii_ctdbPutFldx
#define _ctdbRBLIFILX				ii_ctdbRBLIFILX
#define _ctdbREDIREC				ii_ctdbREDIREC
#define _ctdbREDIVREC				ii_ctdbREDIVREC
#define _ctdbREDVREC				ii_ctdbREDVREC
#define _ctdbREGCTREE				ii_ctdbREGCTREE
#define _ctdbRENIFIL				ii_ctdbRENIFIL
#define _ctdbRWTREC				ii_ctdbRWTREC
#define _ctdbRWTVREC				ii_ctdbRWTVREC
#define _ctdbRWTPREC				ii_ctdbRWTPREC
#define ctdbReadRecord				ii_ctdbReadRecord
#define ctdbRecLock				ii_ctdbRecLock
#define ctdbRecUnlock				ii_ctdbRecUnlock
#define ctdbRecordSetOff			ii_ctdbRecordSetOff
#define ctdbRecordSetOn				ii_ctdbRecordSetOn
#define ctdbReleaseLocks			ii_ctdbReleaseLocks
#define ctdbReleaseTableLocks			ii_ctdbReleaseTableLocks
#define _ctdbRemoveDict				ii_ctdbRemoveDict
#define _ctdbRemoveDictByUID			ii_ctdbRemoveDictByUID
#define ctdbReopenDict				ii_ctdbReopenDict
#define ctdbResetAll				ii_ctdbResetAll
#define ctdbResetRecord				ii_ctdbResetRecord
#define ctdbRestoreSavePoint			ii_ctdbRestoreSavePoint
#define _ctdbSETCURI				ii_ctdbSETCURI
#define _ctdbSWTCTREE				ii_ctdbSWTCTREE
#define ctdbSeekRecord				ii_ctdbSeekRecord
#define ctdbSetDatabaseObjptr			ii_ctdbSetDatabaseObjptr
#define ctdbSetDefDateType			ii_ctdbSetDefDateType
#define ctdbSetDefFloatFormat			ii_ctdbSetDefFloatFormat
#define ctdbSetDefTimeType			ii_ctdbSetDefTimeType
#define ctdbSetDefaultIndex			ii_ctdbSetDefaultIndex
#define ctdbSetEditedRecord			ii_ctdbSetEditedRecord
#define ctdbSetError				ii_ctdbSetError
#define ctdbSetFieldAsBinary			ii_ctdbSetFieldAsBinary
#define ctdbSetFieldAsBlob			ii_ctdbSetFieldAsBlob
#define ctdbSetFieldAsBool			ii_ctdbSetFieldAsBool
#define ctdbSetFieldAsDate			ii_ctdbSetFieldAsDate
#define ctdbSetFieldAsDateTime			ii_ctdbSetFieldAsDateTime
#define ctdbSetFieldAsFloat			ii_ctdbSetFieldAsFloat
#define ctdbSetFieldAsMoney			ii_ctdbSetFieldAsMoney
#define ctdbSetFieldAsSigned			ii_ctdbSetFieldAsSigned
#define ctdbSetFieldAsString			ii_ctdbSetFieldAsString
#define ctdbSetFieldAsTime			ii_ctdbSetFieldAsTime
#define ctdbSetFieldAsUnsigned			ii_ctdbSetFieldAsUnsigned
#define ctdbSetFieldLength			ii_ctdbSetFieldLength
#define ctdbSetFieldName			ii_ctdbSetFieldName
#define ctdbSetFieldNullFlag			ii_ctdbSetFieldNullFlag
#define ctdbSetFieldPrecision			ii_ctdbSetFieldPrecision
#define ctdbSetFieldProperties			ii_ctdbSetFieldProperties
#define ctdbSetFieldScale			ii_ctdbSetFieldScale
#define ctdbSetFieldType			ii_ctdbSetFieldType
#define ctdbIsFieldNumeric			ii_ctdbIsFieldNumeric
#define ctdbSetIndexDuplicateFlag		ii_ctdbSetIndexDuplicateFlag
#define ctdbSetIndexEmptyChar			ii_ctdbSetIndexEmptyChar
#define ctdbSetIndexExtension			ii_ctdbSetIndexExtension
#define ctdbSetIndexKeyType			ii_ctdbSetIndexKeyType
#define ctdbSetIndexNullFlag			ii_ctdbSetIndexNullFlag
#define ctdbSetIndexTemporaryFlag		ii_ctdbSetIndexTemporaryFlag
#define ctdbSetIndexCndxExpr		ii_ctdbSetIndexCndxExpr
#define ctdbSetLockActive			ii_ctdbSetLockActive
#define ctdbSetLockMode				ii_ctdbSetLockMode
#define ctdbSetLogonOnly			ii_ctdbSetLogonOnly
#define ctdbSetNewRecord			ii_ctdbSetNewRecord
#define ctdbSetRecordOffset			ii_ctdbSetRecordOffset
#define ctdbSetRecordPos			ii_ctdbSetRecordPos
#define ctdbSetSegmentMode			ii_ctdbSetSegmentMode
#define ctdbSetSessionParams			ii_ctdbSetSessionParams
#define ctdbSetSessionPath			ii_ctdbSetSessionPath
#define ctdbSetTableDefaultDataExtentSize 	ii_ctdbSetTableDefaultDataExtentSize
#define ctdbSetTableDefaultIndexExtentSize	ii_ctdbSetTableDefaultIndexExtentSize
#define ctdbSetTableExtension			ii_ctdbSetTableExtension
#define ctdbSetTableGroupid			ii_ctdbSetTableGroupid
#define ctdbSetTableObjptr			ii_ctdbSetTableObjptr
#define ctdbSetTablePassword			ii_ctdbSetTablePassword
#define ctdbSetTablePath			ii_ctdbSetTablePath
#define ctdbSetTablePermission			ii_ctdbSetTablePermission
#define ctdbSetTableSuperFile			ii_ctdbSetTableSuperFile
#define ctdbSetUserTag				ii_ctdbSetUserTag
#define _ctdbStartDebug				ii_ctdbStartDebug
#define ctdbStringToDate			ii_ctdbStringToDate
#define ctdbStringToDateTime			ii_ctdbStringToDateTime
#define ctdbStringToMoney			ii_ctdbStringToMoney
#define ctdbStringToTime			ii_ctdbStringToTime
#define _ctdbSuperClose				ii_ctdbSuperClose
#define _ctdbSuperCreate				ii_ctdbSuperCreate
#define _ctdbSuperDrop				ii_ctdbSuperDrop
#define _ctdbSuperOpen				ii_ctdbSuperOpen
#define _ctdbSuperReopen				ii_ctdbSuperReopen
#define _ctdbSuperSetName			ii_ctdbSuperSetName
#define _ctdbSuperSetPath			ii_ctdbSuperSetPath
#define _ctdbSysTime				ii_ctdbSysTime
#define _ctdbTFRMKEY				ii_ctdbTFRMKEY
#define ctdbTimeCheck				ii_ctdbTimeCheck
#define ctdbTimePack				ii_ctdbTimePack
#define ctdbTimeToString			ii_ctdbTimeToString
#define ctdbTimeUnpack				ii_ctdbTimeUnpack
#define _ctdbUNRCTREE				ii_ctdbUNRCTREE
#define ctdbUnlock				ii_ctdbUnlock
#define _ctdbUnlockDict				ii_ctdbUnlockDict
#define ctdbUnlockRecord			ii_ctdbUnlockRecord
#define ctdbUnlockTable				ii_ctdbUnlockTable
#define ctdbUpdLock				ii_ctdbUpdLock
#define _ctdbWriteDict				ii_ctdbWriteDict
#define ctdbWriteRecord				ii_ctdbWriteRecord
#define _ctdb_FullPath				ii_ctdb_FullPath
#define _ctdb_GetFileExt				ii_ctdb_GetFileExt
#define _ctdb_GetFileName			ii_ctdb_GetFileName
#define _ctdb_GetFilePath			ii_ctdb_GetFilePath
#ifdef CTDB_MIRROR
#define _ctdb_GetMirrorFileName			ii_ctdb_GetMirrorFileName
#endif
#define _ctdbfrmkey				ii_ctdbfrmkey
#define ctdbGetFieldType			ii_ctdbGetFieldType
#define ctdbAddField				ii_ctdbAddField
#define ctdbAddIndex				ii_ctdbAddIndex
#define ctdbAddSegment				ii_ctdbAddSegment
#define ctdbAddSegmentByName			ii_ctdbAddSegmentByName
#define ctdbAddSegmentByNbr			ii_ctdbAddSegmentByNbr
#define ctdbAddSegmentEx			ii_ctdbAddSegmentEx
#define ctdbAllocDatabase			ii_ctdbAllocDatabase
#define ctdbAllocRecord				ii_ctdbAllocRecord
#define ctdbAllocSession			ii_ctdbAllocSession
#define ctdbAllocTable				ii_ctdbAllocTable
#define ctdbDuplicateRecord			ii_ctdbDuplicateRecord
#define ctdbFindActiveDatabase			ii_ctdbFindActiveDatabase
#define ctdbFindActiveDatabaseByUID		ii_ctdbFindActiveDatabaseByUID
#define ctdbFindActiveTable			ii_ctdbFindActiveTable
#define ctdbFindActiveTableByUID		ii_ctdbFindActiveTableByUID
#define ctdbGetActiveTableByUID			ii_ctdbGetActiveTableByUID
#define ctdbGetDatabaseHandle			ii_ctdbGetDatabaseHandle
#define ctdbGetField				ii_ctdbGetField
#define ctdbGetFieldByName			ii_ctdbGetFieldByName
#define ctdbGetFieldHandle			ii_ctdbGetFieldHandle
#define ctdbGetFirstActiveDatabase		ii_ctdbGetFirstActiveDatabase
#define ctdbGetFirstActiveTable			ii_ctdbGetFirstActiveTable
#define ctdbGetIndex				ii_ctdbGetIndex
#define ctdbGetIndexByName			ii_ctdbGetIndexByName
#define ctdbGetIndexByUID			ii_ctdbGetIndexByUID
#define ctdbGetIndexHandle			ii_ctdbGetIndexHandle
#define ctdbGetNextActiveDatabase		ii_ctdbGetNextActiveDatabase
#define ctdbGetNextActiveTable			ii_ctdbGetNextActiveTable
#define ctdbGetRecord				ii_ctdbGetRecord
#define ctdbGetRecordHandle			ii_ctdbGetRecordHandle
#define ctdbGetSegment				ii_ctdbGetSegment
#define ctdbGetSegmentField			ii_ctdbGetSegmentField
#define ctdbGetSegmentPartialField		ii_ctdbGetSegmentPartialField
#define ctdbGetSegmentHandle			ii_ctdbGetSegmentHandle
#define ctdbGetSessionHandle			ii_ctdbGetSessionHandle
#define ctdbGetTable				ii_ctdbGetTable
#define ctdbGetTableHandle			ii_ctdbGetTableHandle
#define ctdbInsField				ii_ctdbInsField
#define ctdbInsFieldByName			ii_ctdbInsFieldByName
#define ctdbInsSegment				ii_ctdbInsSegment
#define ctdbInsSegmentByName			ii_ctdbInsSegmentByName
#define ctdbInsSegmentByNbr			ii_ctdbInsSegmentByNbr
#define ctdbInsSegmentEx			ii_ctdbInsSegmentEx
#define _ctdbSelectHandle			ii_ctdbSelectHandle
#define ctdbGetLockMode				ii_ctdbGetLockMode
#define ctdbMoneyAbs				ii_ctdbMoneyAbs
#define ctdbGetTableOpenMode			ii_ctdbGetTableOpenMode
#define ctdbGetSegmentMode			ii_ctdbGetSegmentMode
#define ctdbGetDefTimeType			ii_ctdbGetDefTimeType
#define ctdbGetTablePermission			ii_ctdbGetTablePermission
#define _ctdbDictGetDatabaseCount		ii_ctdbDictGetDatabaseCount
#define _ctdbDictGetTableCount			ii_ctdbDictGetTableCount
#define ctdbGetDatabaseCount			ii_ctdbGetDatabaseCount
#define _ctdbGetDictCount			ii_ctdbGetDictCount
#define ctdbGetFieldNbr				ii_ctdbGetFieldNbr
#define ctdbGetFieldPrecision			ii_ctdbGetFieldPrecision
#define ctdbGetFieldScale			ii_ctdbGetFieldScale
#define ctdbGetIndexEmptyChar			ii_ctdbGetIndexEmptyChar
#define ctdbGetIndexNbrByName			ii_ctdbGetIndexNbrByName
#define ctdbGetSessionParams			ii_ctdbGetSessionParams
#define ctdbGetRecordNbr			ii_ctdbGetRecordNbr
#define ctdbGetTableCount			ii_ctdbGetTableCount
#define ctdbGetTableDefaultDataExtentSize	ii_ctdbGetTableDefaultDataExtentSize
#define ctdbGetTableDefaultIndexExtentSize	ii_ctdbGetTableDefaultIndexExtentSize
#define ctdbGetTableNbr				ii_ctdbGetTableNbr
#define _ctdbListCount				ii_ctdbListCount
#define _ctdbListIndexOf				ii_ctdbListIndexOf
#define _ctdbListSize				ii_ctdbListSize
#define _ctdbLocateDatabase			ii_ctdbLocateDatabase
#define _ctdbLocateTable				ii_ctdbLocateTable
#define ctdbLockCount				ii_ctdbLockCount
#define ctdbGetIndexUID				ii_ctdbGetIndexUID
#define ctdbBlobGetSize				ii_ctdbBlobGetSize
#define ctdbGetFieldDataLength			ii_ctdbGetFieldDataLength
#define ctdbGetFieldLength			ii_ctdbGetFieldLength
#define ctdbGetFieldNumberByName		ii_ctdbGetFieldNumberByName
#define ctdbGetFieldOffset			ii_ctdbGetFieldOffset
#define ctdbGetFieldSize			ii_ctdbGetFieldSize
#define ctdbGetIndexKeyLength			ii_ctdbGetIndexKeyLength
#define ctdbGetIndexSegmentCount		ii_ctdbGetIndexSegmentCount
#define ctdbGetRecordLength			ii_ctdbGetRecordLength
#define ctdbGetRecordSize			ii_ctdbGetRecordSize
#define ctdbGetTableFieldCount			ii_ctdbGetTableFieldCount
#define ctdbGetTableIndexCount			ii_ctdbGetTableIndexCount
#define _ctdb_lastdelimiter			ii_ctdb_lastdelimiter
#define ctdbBlobCmp				ii_ctdbBlobCmp
#define ctdbGetDefaultIndex			ii_ctdbGetDefaultIndex
#define ctdbGetFieldNumber			ii_ctdbGetFieldNumber
#define _ctdbGetHandleId				ii_ctdbGetHandleId
#define ctdbMoneyCmp				ii_ctdbMoneyCmp
#define ctdbSetSavePoint			ii_ctdbSetSavePoint
#define ctdbSetSingleSavePoint			ii_ctdbSetSingleSavePoint
#define ctdbBlobAlloc				ii_ctdbBlobAlloc
#define ctdbGetFieldData			ii_ctdbGetFieldData
#define _ctdbAllocDict				ii_ctdbAllocDict
#define ctdbAllocField				ii_ctdbAllocField
#define _ctdbAllocFldx				ii_ctdbAllocFldx
#define ctdbAllocIndex				ii_ctdbAllocIndex
#define ctdbAllocSegment			ii_ctdbAllocSegment
#define _ctdbListAlloc				ii_ctdbListAlloc
#define _ctdbListDup				ii_ctdbListDup
#define _ctdbListFree				ii_ctdbListFree
#define _ctdbListDeleteEx			ii_ctdbListDeleteEx
#define ctdbFindLock				ii_ctdbFindLock
#define ctdbLockItem				ii_ctdbLockItem
#define _ctdbAllocLock				ii_ctdbAllocLock
#define _ctdbFreeLock				ii_ctdbFreeLock
#define ctdbGetTableSuperFile			ii_ctdbGetTableSuperFile
#define _ctdbSuperAlloc				ii_ctdbSuperAlloc
#define _ctdbSuperFree				ii_ctdbSuperFree
#define _ctdbFieldTypeName			ii_ctdbFieldTypeName
#define ctdbGetDatabaseName			ii_ctdbGetDatabaseName
#define ctdbGetDatabasePath			ii_ctdbGetDatabasePath
#define ctdbGetDefFloatFormat			ii_ctdbGetDefFloatFormat
#define ctdbGetFieldName			ii_ctdbGetFieldName
#define ctdbGetIndexExtension			ii_ctdbGetIndexExtension
#define ctdbGetSegmentFieldName			ii_ctdbGetSegmentFieldName
#define ctdbGetServerName			ii_ctdbGetServerName
#define ctdbGetTableExtension			ii_ctdbGetTableExtension
#define ctdbGetTableGroupid			ii_ctdbGetTableGroupid
#define ctdbGetTableName			ii_ctdbGetTableName
#define ctdbGetTablePassword			ii_ctdbGetTablePassword
#define ctdbGetTablePath			ii_ctdbGetTablePath
#define ctdbGetUserLogonName			ii_ctdbGetUserLogonName
#define ctdbGetUserPassword			ii_ctdbGetUserPassword
#define _ctdbSuperGetName			ii_ctdbSuperGetName
#define _ctdb_MakeFilePath			ii_ctdb_MakeFilePath
#define _ctdb_stralloc				ii_ctdb_stralloc
#define _ctdb_strdup				ii_ctdb_strdup
#define _ctdb_strlastchar			ii_ctdb_strlastchar
#define ctdbBlobGetData				ii_ctdbBlobGetData
#define ctdbGetDatabaseObjptr			ii_ctdbGetDatabaseObjptr
#define ctdbGetFieldAddress			ii_ctdbGetFieldAddress
#define ctdbGetRecordBuffer			ii_ctdbGetRecordBuffer
#define ctdbGetTableObjptr			ii_ctdbGetTableObjptr
#define _ctdbListItem				ii_ctdbListItem
#define _ctdb_alloc				ii_ctdb_alloc
#define _ctdb_free				ii_ctdb_free
#define _ctdb_realloc				ii_ctdb_realloc
#define ctdbBlobFree				ii_ctdbBlobFree
#define _ctdbClearBit				ii_ctdbClearBit
#define ctdbClearError				ii_ctdbClearError
#define _ctdbFileNameOnly			ii_ctdbFileNameOnly
#define _ctdbFlipBit				ii_ctdbFlipBit
#define ctdbFreeDatabase			ii_ctdbFreeDatabase
#define _ctdbFreeDict				ii_ctdbFreeDict
#define ctdbFreeField				ii_ctdbFreeField
#define ctdbFreeIndex				ii_ctdbFreeIndex
#define ctdbFreeRecord				ii_ctdbFreeRecord
#define ctdbFreeSegment				ii_ctdbFreeSegment
#define ctdbFreeSession				ii_ctdbFreeSession
#define ctdbFreeTable				ii_ctdbFreeTable
#define _ctdbSetBit				ii_ctdbSetBit
#define ctdbCloneTable				ii_ctdbCloneTable
#define ctdbHelloWorld				ii_ctdbHelloWorld	/* CTDB HELLO WORLD */

#endif /* CTDBCEPTLAYER	If intercept layer defined */

