/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class faircom_rtg_CtreeEnv */

#ifndef _Included_faircom_rtg_CtreeEnv
#define _Included_faircom_rtg_CtreeEnv
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     faircom_rtg_CtreeEnv
 * Method:    ct_LibType
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_faircom_rtg_CtreeEnv_ct_1LibType
  (JNIEnv *, jclass);

/*
 * Class:     faircom_rtg_CtreeEnv
 * Method:    ct_init
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_faircom_rtg_CtreeEnv_ct_1init
  (JNIEnv *, jclass, jlong);

/*
 * Class:     faircom_rtg_CtreeEnv
 * Method:    ct_exit
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_faircom_rtg_CtreeEnv_ct_1exit
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     faircom_rtg_CtreeEnv
 * Method:    ct_exitsrv
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_faircom_rtg_CtreeEnv_ct_1exitsrv
  (JNIEnv *, jclass);

/*
 * Class:     faircom_rtg_CtreeEnv
 * Method:    ct_initsrv
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_faircom_rtg_CtreeEnv_ct_1initsrv
  (JNIEnv *, jclass);

/*
 * Class:     faircom_rtg_CtreeEnv
 * Method:    ct_sync
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_faircom_rtg_CtreeEnv_ct_1sync
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     faircom_rtg_CtreeEnv
 * Method:    ct_remove
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_faircom_rtg_CtreeEnv_ct_1remove
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     faircom_rtg_CtreeEnv
 * Method:    ct_rename
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_faircom_rtg_CtreeEnv_ct_1rename
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     faircom_rtg_CtreeEnv
 * Method:    ct_version
 * Signature: (J[B[B[BI[I)I
 */
JNIEXPORT jint JNICALL Java_faircom_rtg_CtreeEnv_ct_1version
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jbyteArray, jint, jintArray);

/*
 * Class:     faircom_rtg_CtreeEnv
 * Method:    ct_copy
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_faircom_rtg_CtreeEnv_ct_1copy
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     faircom_rtg_CtreeEnv
 * Method:    ct_begin
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_faircom_rtg_CtreeEnv_ct_1begin
  (JNIEnv *, jclass, jlong);

/*
 * Class:     faircom_rtg_CtreeEnv
 * Method:    ct_commit
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_faircom_rtg_CtreeEnv_ct_1commit
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     faircom_rtg_CtreeEnv
 * Method:    ct_rollback
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_faircom_rtg_CtreeEnv_ct_1rollback
  (JNIEnv *, jclass, jlong);

/*
 * Class:     faircom_rtg_CtreeEnv
 * Method:    ct_recover
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_faircom_rtg_CtreeEnv_ct_1recover
  (JNIEnv *, jclass, jlong);

/*
 * Class:     faircom_rtg_CtreeEnv
 * Method:    ct_make
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[BB)I
 */
JNIEXPORT jint JNICALL Java_faircom_rtg_CtreeEnv_ct_1make
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring, jstring, jstring, jbyteArray, jbyte);

/*
 * Class:     faircom_rtg_CtreeEnv
 * Method:    ct_open
 * Signature: (JLjava/lang/String;ILjava/lang/String;B)J
 */
JNIEXPORT jlong JNICALL Java_faircom_rtg_CtreeEnv_ct_1open
  (JNIEnv *, jclass, jlong, jstring, jint, jstring, jbyte);

/*
 * Class:     faircom_rtg_CtreeEnv
 * Method:    ct_sqllink
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;BLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_faircom_rtg_CtreeEnv_ct_1sqllink
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring, jstring, jstring, jbyte, jstring);

/*
 * Class:     faircom_rtg_CtreeEnv
 * Method:    ct_config
 * Signature: (IJJLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_faircom_rtg_CtreeEnv_ct_1config
  (JNIEnv *, jclass, jint, jlong, jlong, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     faircom_rtg_CtreeEnv
 * Method:    ct_config2
 * Signature: (IJJ[Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_faircom_rtg_CtreeEnv_ct_1config2
  (JNIEnv *, jclass, jint, jlong, jlong, jobjectArray);

/*
 * Class:     faircom_rtg_CtreeEnv
 * Method:    ct_intfversion
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_faircom_rtg_CtreeEnv_ct_1intfversion
  (JNIEnv *, jclass, jint);

/*
 * Class:     faircom_rtg_CtreeEnv
 * Method:    ct_lockerid
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_faircom_rtg_CtreeEnv_ct_1lockerid
  (JNIEnv *, jclass, jlong);

/*
 * Class:     faircom_rtg_CtreeEnv
 * Method:    ct_logons
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_faircom_rtg_CtreeEnv_ct_1logons
  (JNIEnv *, jclass, jlong);

/*
 * Class:     faircom_rtg_CtreeEnv
 * Method:    ct_close
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_faircom_rtg_CtreeEnv_ct_1close
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     faircom_rtg_CtreeEnv
 * Method:    ct_read
 * Signature: (JJ[BIIS)I
 */
JNIEXPORT jint JNICALL Java_faircom_rtg_CtreeEnv_ct_1read
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint, jshort);

/*
 * Class:     faircom_rtg_CtreeEnv
 * Method:    ct_next
 * Signature: (JJ[BIS)I
 */
JNIEXPORT jint JNICALL Java_faircom_rtg_CtreeEnv_ct_1next
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jshort);

/*
 * Class:     faircom_rtg_CtreeEnv
 * Method:    ct_previous
 * Signature: (JJ[BIS)I
 */
JNIEXPORT jint JNICALL Java_faircom_rtg_CtreeEnv_ct_1previous
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jshort);

/*
 * Class:     faircom_rtg_CtreeEnv
 * Method:    ct_start
 * Signature: (JJ[BIIII)I
 */
JNIEXPORT jint JNICALL Java_faircom_rtg_CtreeEnv_ct_1start
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint, jint, jint);

/*
 * Class:     faircom_rtg_CtreeEnv
 * Method:    ct_write
 * Signature: (JJ[BIIS)I
 */
JNIEXPORT jint JNICALL Java_faircom_rtg_CtreeEnv_ct_1write
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint, jshort);

/*
 * Class:     faircom_rtg_CtreeEnv
 * Method:    ct_rewrite
 * Signature: (JJ[BIIS)I
 */
JNIEXPORT jint JNICALL Java_faircom_rtg_CtreeEnv_ct_1rewrite
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint, jshort);

/*
 * Class:     faircom_rtg_CtreeEnv
 * Method:    ct_delete
 * Signature: (JJ[BI)I
 */
JNIEXPORT jint JNICALL Java_faircom_rtg_CtreeEnv_ct_1delete
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint);

/*
 * Class:     faircom_rtg_CtreeEnv
 * Method:    ct_unlock
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_faircom_rtg_CtreeEnv_ct_1unlock
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     faircom_rtg_CtreeEnv
 * Method:    ct_info
 * Signature: (JJI[B)I
 */
JNIEXPORT jint JNICALL Java_faircom_rtg_CtreeEnv_ct_1info
  (JNIEnv *, jclass, jlong, jlong, jint, jbyteArray);

/*
 * Class:     faircom_rtg_CtreeEnv
 * Method:    ct_sqlinfo
 * Signature: (JJLjava/lang/String;B)I
 */
JNIEXPORT jint JNICALL Java_faircom_rtg_CtreeEnv_ct_1sqlinfo
  (JNIEnv *, jclass, jlong, jlong, jstring, jbyte);

/*
 * Class:     faircom_rtg_CtreeEnv
 * Method:    ct_get_f_errno
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_faircom_rtg_CtreeEnv_ct_1get_1f_1errno
  (JNIEnv *, jclass, jlong);

/*
 * Class:     faircom_rtg_CtreeEnv
 * Method:    ct_get_f_int_errno
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_faircom_rtg_CtreeEnv_ct_1get_1f_1int_1errno
  (JNIEnv *, jclass, jlong);

/*
 * Class:     faircom_rtg_CtreeEnv
 * Method:    ct_get_f_int2_errno
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_faircom_rtg_CtreeEnv_ct_1get_1f_1int2_1errno
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
